Configs: &Default
  Version: 2
  AppName: MobileAppSample
  AgreementSettings:
    Content: offer.html
  ServerSettings:
    VerifyPhoneCodeLength: 6
    ForceDisableInputSocial: False
  Analytics:
    Google: 
      Enable: false
      TrackerId:
        Android: 
        Ios: 
      Interval:
        Android: 5
        Ios: 5
  CachePolicyEnabled: False
  CaptchaSettings:
    BaseUrl: http://localhost
    SiteKey:
      Ios: "6LdxdXAUAAAAAP2s6x21Wr0CWfsYVDzddgHPxcHl"
      Android: "6Lco4XAUAAAAAMm_wZt1953xjtB8dwz7a4-H_Wkt"
  ResendCodeConfirmTime: 15 #Время ожидания для повторной отправки кода подтверждения (секунды)
  AnonymVirtualCard: False #Виртуальная карта для анонима 
  ShowOptions:
    ProfileCardViewModel: OnlyAuth #Отображать в меню "Моя карта" All or OnlyAuth
    PersonalOffersViewModel: OnlyAuth #Отображать в меню "Персональные акции" OnlyAuth or Never
    PersonalGoodsViewModel: OnlyAuth #Отображать в меню "Любимые товары" OnlyAuth or Never
  Localization:
    Enable: True #Подключение локализации
    ViewLocalization: True #Отображение стартового экрана с выбором языка при первом запуске приложения

Development:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://api-demo.loymax.tech/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: False
      Ios: False
    EnableCrashManager: False
    EnableUpdateManager: False
  PushNotification: 
    Enable: False
    ProjectNumber:
      Android: ""

Staging:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://api-demo.loymax.tech/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp:
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
    EnableUpdateManager: True
  PushNotification: 
    Enable: False
    ProjectNumber:
      Android: ""

Production:
  <<: *Default
  LoymaxEndpoint:
    AppUrl: https://api-demo.loymax.tech/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
    EnableUpdateManager: False
  PushNotification: 
    Enable: False
    ProjectNumber:
      Android: ""